### ISSUE TITLE
Static libraries

### ISSUE THREAD

**Issue by wiktor** [Polidea/ios-class-guard#14]
Currently static libraries are not supported. I understand that securing apps (not libs) is more common use case.

Is it just a matter of configuring the tool? That is providing list of files to obfuscate (.h .m) along with public header files that should not be obfuscated as entry point?

**Comment by truist** [comment]
Hi, I know this issue is old, but I thought you might like to know that we just released a new version of [PPiOS-Rename](https://github.com/preemptive/PPiOS-Rename) (which is a fork and evolution of ios-class-guard) that has support for [obfuscating static libraries](https://github.com/preemptive/PPiOS-Rename#obfuscating-static-libraries), at least in that there's a well-documented workaround that makes it possible to do so.
